### ISSUE TITLE
Translations misssing?

### ISSUE THREAD

**Issue by matclou** [jsegaert/iocage-plugin-heimdall#5]
Hi,

while installing this plugin (version 2.5.7) in TrueNAS-13.0-U4 (which generally worked) I just noticed, that only the English language was available in the settings for the GUI - even though, in an older Installation (2.2.3) multiple languages were available.

Does anyone face similar issues? Is this an issue of the plugin, the actual software or am I missing something?

Best regards

matclou

**Comment by jsegaert** [comment]
Thanks for reporting!  I checked the upstream project, and it turns out that the issue with the language list was reported in the issue below.  I recommend to add your comments and details, e.g. the specific release etc.. to help the developers track it down.

https://github.com/linuxserver/Heimdall/issues/1119

**Comment by matclou** [comment]
Hi! Thanks for your reply! I added my details in this issue. (However I am not 100 % whether it is the same issue, as geralddurbas (https://github.com/geraldurbas) wrote that the language list was completely empty (while in my case at least the English language was avaialble)).
